name: Export Game

on:
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: macOS-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Download Godot 3.5.1
      run: |
        wget https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_osx.64.zip
        unzip Godot_v3.5.1-stable_osx.64.zip
    
    - name: Export Game
      run: |
        ./Godot_v3.5.1-stable_osx.64 --export "Platform" /path/to/exported/game
    
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Exported Game
        path: /path/to/exported/game
