name: Export iOS app

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Godot
        uses: firebelley/godot-export@v5.1.0
        with:
          godot-version: 3.5.1

      - name: Export iOS app
        uses: firebelley/godot-export@v5.1.0
        with:
          godot-project: .
          platform: ios
          export-presets: 'debug'
          export-path: './export'
          export-name: 'MyGame'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MyGame-iOS
          path: ./export/MyGame.ipa
