name: iOS Export
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Export iOS
      uses: firebelley/godot-export@v5.1.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_osx.universal.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_export_templates.tpz
        relative_project_path: './'
        export_preset: export_presets
        export_debug: true
        export_as_pack: true
    - name: Install Xcode
      uses: actions/setup-xcode@v2.4.0
      with:
        xcode-version: "13.2"
    - name: Build iOS
      run: xcodebuild -workspace path/to/your.xcworkspace -scheme "Scheme Name" -configuration Release -archivePath $HOME/build.xcarchive archive -quiet
    - name: Export IPA
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ios-artifact
        path: $HOME/build.xcarchive/Products/Applications/*.app

