name: iOS Export
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Export iOS
      uses: firebelley/godot-export@v5.1.0
      with:
        platform: ios
        export_path: path/to/exported/game
        godot_version: 3.5.1
