name: iOS Export

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '13.x'
    - name: Install Dependencies
      run: |
        brew install pkg-config
        brew install libzip
        brew install wget
    - name: Export iOS
      run: |
        wget https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_osx.universal.zip
        unzip Godot_v3.5.1-stable_osx.universal.zip
        chmod +x Godot_v3.5.1-stable_osx.universal/Godot\ Engine.app/Contents/MacOS/Godot
        wget https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_export_templates.tpz
        ./Godot_v3.5.1-stable_osx.universal/Godot\ Engine.app/Contents/MacOS/Godot --export "iOS" /Users/runner/work/your-repo-name/your-repo-name/project.godot /Users/runner/work/your-repo-name/your-repo-name/builds/iOS/YourAppName.ipa
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: iOS Build
        path: /Users/runner/work/your-repo-name/your-repo-name/builds/iOS/YourAppName.ipa
