name: iOS Export

on:
  push:
    branches: [main]

jobs:
  export:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: firebelley/godot-export@v5.1.0
      with:
        platform: ios
        export_presets: export_presets
    - name: Archive exported game
      run: |
        cd export/iOS
        zip -r my_game_ios.zip .
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_game_ios
        path: export/iOS/my_game_ios.zip
