name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Godot Engine
      run: |
        curl -sSL "https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_osx.universal.zip" -o godot.zip
        unzip godot.zip
        chmod +x Godot.app/Contents/MacOS/Godot || exit 1
        ls -l Godot.app/Contents/MacOS/ # Optional: List the contents of the folder for troubleshooting
        
    - name: Install Xcode
      uses: actions/setup-node@v2
      with:
        node-version: "14"
        xcode-version: "12.x"
    
    - name: Build for iOS
      run: |
        Godot_v3.5.1-stable_osx.universal/Godot.app/Contents/MacOS/Godot --export "iOS" /path/to/exported/game
        # Additional build and test commands
