name: "Godot Export Example"
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GODOT_VERSION: 3.5.1
  PROJECT_PATH: game
  EXPORT_MODE: release # If not defined, defaults to debug
  # Required if in release mode
  # K8S_SECRET_RELEASE_KEYSTORE_BASE64: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_BASE64 }}
  # K8S_SECRET_RELEASE_KEYSTORE_USER: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_USER }}
  # K8S_SECRET_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.K8S_SECRET_RELEASE_KEYSTORE_PASSWORD }}
  GAME_VERSION_TAG: game/version # Defined In Godot's Editor Project Settings - Path To Custom Variable
  ITCH_GAME: itchio-game
  ITCH_USER: itchio-user

jobs:
  export:
    name: "Godot Project Export"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Godot
        run: |
          curl -LO https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}.stable.macosx.64.zip
          unzip Godot_v${{ env.GODOT_VERSION }}.stable.macosx.64.zip
          chmod +x Godot_v${{ env.GODOT_VERSION }}.stable.macosx.64/Godot
          sudo mv Godot_v${{ env.GODOT_VERSION }}.stable.macosx.64/Godot /usr/local/bin/godot
          rm Godot_v${{ env.GODOT_VERSION }}.stable.macosx.64.zip

      - name: Export iOS Version
        run: |
          godot --export "iOS" ${{ env.PROJECT_PATH }}/export/ios/game.ipa

      - name: Publish iOS Version
        uses: vini-guerrero/godot-exporter/actions/publish@master
        with:
          platform: "Itch"
          channel: "iOS"
          project_path: ${{ env.PROJECT_PATH }}/export/ios/game.ipa

      - name: Archive iOS Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iOS
          path: ${{ env.PROJECT_PATH }}/export/ios/game.ipa
