name: Godot iOS Export

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Set up Godot
        run: |
          wget https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_export_templates.tpz
          unzip Godot_v3.5.1-stable_export_templates.tpz
          mkdir -p ~/.godot/templates
          mv templates ~/.godot/templates

      - name: Build iOS export
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          godot --export "iOS" .

      - name: Upload iOS export
        uses: actions/upload-artifact@v2
        with:
          name: iOS-export
          path: iOS_export
