name: iOS Export

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create iOS directory
      run: mkdir -p ios

    - name: Export iOS
      uses: firebelley/godot-export@v5.1.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_osx.universal.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_export_templates.tpz
        relative_project_path: './'
        export_preset: export_presets
        export_debug: true
        export_as_pack: true
        export_path: './ios/game.ipa'
        
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: iOS Build
        path: ./ios/

    - name: Install Xcode
      uses: sinoru/actions-setup-xcode@v2.0.2
      with:
        version: '13.4'    
    - run: fastlane scan
    
    - name: Build iOS App
      run: |
        cd ios
        xcodebuild archive -allowProvisioningUpdates -workspace YourWorkspaceName.xcworkspace -scheme YourSchemeName -archivePath aaa.xcarchive

    - name: Export IPA
      uses: actions/upload-artifact@v2
      with:
        name: iOS Build
        path: ./ios/aaa.xcarchive/Products/Applications/aaa.ipa
