name: Export Godot Game
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Godot
        run: curl -LO https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_macos.64.zip

      - name: Unzip Godot
        run: unzip Godot_v3.5.1-stable_macos.64.zip

      - name: Export game
        run: ./exported_files/Godot.app/Contents/MacOS/Godot --export "Mac OSX" ${{ github.workspace }}/project.godot path_to_export/game_mac.zip
