name: iOS Export

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Godot
      uses: lihop/setup-godot@v2.1.0

    - name: Export iOS game
      run: godot --export "iOS" path/to/export/game.ipa

    - name: Copy exported game
      run: cp path/to/export/game.ipa ${{ github.workspace }}/game.ipa

    - name: Upload game
      uses: actions/upload-artifact@v2
      with:
        name: exported-game
        path: ${{ github.workspace }}/game.ipa
