name: iOS Export

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Godot
        uses: rafaelalmeidatk/godot-install@v1
        with:
          godot-version: '3.3.3'

      - name: Install Xcode
        run: sudo xcode-select --install

      - name: Install iOS Dependencies
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer && sudo xcodebuild -runFirstLaunch

      - name: Install iOS Plugins
        run: godot --gdnative-generate-json-api && godot --gdnative-generate-gir-api

      - name: Export Game for iOS
        run: godot --export "iOS" /path/to/export/dir

      - name: Sign Game
        run: /usr/bin/xcrun xcodebuild -exportArchive -archivePath /path/to/archive.xcarchive -exportOptionsPlist /path/to/exportOptions.plist -exportPath /path/to/export/dir

      - name: Upload Game to App Store Connect
        uses: transporter-action@v2
        with:
          username: ${{ secrets.APPLE_ID }}
          password: ${{ secrets.APP_PASSWORD }}
          bundle_id: com.yourcompany.yourgame
          ipa_path: /path/to/export/dir/YourGame.ipa
