name: Export Game

on:
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Godot
      run: |
        sudo apt update
        sudo apt install -y godot3.5
    
    - name: Export Game
      run: |
        godot3.5 --export "Platform" /path/to/exported/game
    
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Exported Game
        path: /path/to/exported/game
